#==========================================================
#= Ordini Web Service - Versione Base
#==========================================================
server:
  port: 8081
  localPort: 8081
  
spring:
  application:
    name: ordini
#==========================================================
#= PARAMETRI DBMS MYSQL
#==========================================================
  sql:
    init:
      mode: always
      platform: mySql
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: 123stella
    url: jdbc:mysql://localhost:3306/restaurant
    username: restaurantAppMs
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

